-- =====================================================================
--  gsat-staging — SCHEMA BOOTSTRAP
--
--  🛑 STAGING ONLY. NEVER RUN THIS AGAINST PRODUCTION.
--
--  Implements STAGING_PLAN.md section 3.1. Generated by concatenating the
--  repository's own migration files verbatim — nothing is retyped — so
--  staging starts from exactly the state Production is in.
--
--  Generated from commit : bc84a49
--  Branch                : claude/security-architecture-continuation-i3hw1y
--
--  ------------------------------------------------------------------
--  WHAT THIS DELIBERATELY INSTALLS **UNFIXED**
--  ------------------------------------------------------------------
--  Staging must reproduce the bugs BEFORE they are fixed, or a green
--  test run afterwards proves nothing (STAGING_PLAN.md section 7).
--  So this script installs, on purpose:
--
--    * admin_grant_premium / admin_revoke_premium  -- pre-A1 bodies:
--      no authorization check, no search_path, EXECUTE granted to
--      PUBLIC and anon.                   (findings 9.3 + 9.15)
--    * is_premium_member / claim_pack_with_token   -- no pinned
--      search_path.                                     (finding 9.7)
--    * is_admin()  -- hard-coded email comparison.      (finding 9.6)
--
--  Do NOT "improve" any of these here. They are fixed later, by the A1
--  artefacts, and the difference is what the tests measure.
--
--  ------------------------------------------------------------------
--  ORDERING NOTE  -- this is not arbitrary
--  ------------------------------------------------------------------
--  Two migrations define claim_pack_with_token(text, text) with the SAME
--  signature but DIFFERENT behaviour:
--
--    add_site_to_user_pack_claims.sql  -- honours p_site  (correct)
--    add_premium_memberships.sql       -- IGNORES p_site  (finding 9.5)
--
--  Production behaves as though p_site is ignored, so add_premium_
--  memberships.sql must be applied LAST of the two. That is why the
--  add_site migration sits in section 2-4 and premium_memberships in
--  section 7 -- reordering them would silently make staging diverge
--  from Production.
--
--  ------------------------------------------------------------------
--  RUN THIS ONCE, ON A FRESH PROJECT
--  ------------------------------------------------------------------
--  The upstream migrations contain CREATE INDEX and CREATE POLICY
--  statements without IF NOT EXISTS guards, so a second run fails on
--  duplicates. That is a property of the source files and is left
--  as-is deliberately -- adding guards would mean this script no longer
--  reproduces Production verbatim. If you must re-run it, reset the
--  database first: Dashboard -> Settings -> Database -> Reset database.
--
--  ------------------------------------------------------------------
--  DELIBERATELY NOT CREATED  (STAGING_PLAN.md section 3.2)
--  ------------------------------------------------------------------
--  exams and the whole GSAT exam domain (RESERVED) - level_words and its
--  2.1 MB seeds - user_word_progress - site_settings - all blog_* tables
--  - the 22 LMS/Writing tables - essay_submissions - the essays/Essays
--  buckets.
--
--  Consequence to expect: app pages that read those tables may error on
--  staging. That is EXPECTED and is not a finding. None of S1-S5 needs
--  them.
--
--  ------------------------------------------------------------------
--  NOT INCLUDED HERE, ON PURPOSE
--  ------------------------------------------------------------------
--  The staging-only is_admin() override (STAGING_PLAN.md section 3.3) is
--  a SEPARATE step. It is the one edit that must never reach Production,
--  so it is kept in its own script rather than buried in this one.
-- =====================================================================

BEGIN;

-- #####################################################################
-- #  1. Core pack schema
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/schema.sql
--  packs, pack_items, invite_tokens, user_pack_claims, claim_pack_with_token(1-arg), generate_short_token
-- =====================================================================
-- =====================================================
-- Mock Exam Ace - Vocabulary Pack Schema
-- Run this in Supabase SQL Editor
-- =====================================================

-- =====================================================
-- 1. PACKS: 單字包主表
-- =====================================================
create table if not exists packs (
  id uuid primary key default gen_random_uuid(),

  -- 基本資訊
  title text not null,
  description text,
  theme text,                    -- 主題分類：環境議題、社會議題、商務英語...
  difficulty text,               -- 難度：初級、中級、中高級、高級

  -- 建立者
  created_by uuid references auth.users(id) on delete set null,

  -- 狀態
  is_public boolean default false,  -- 是否公開（公開的 pack 不需要 token 即可查看）
  is_active boolean default true,   -- 是否啟用

  -- 時間戳記
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 索引
create index idx_packs_created_by on packs(created_by);
create index idx_packs_theme on packs(theme);
create index idx_packs_is_public on packs(is_public);

-- =====================================================
-- 2. PACK_ITEMS: 單字包內容（單字列表）
-- =====================================================
create table if not exists pack_items (
  id uuid primary key default gen_random_uuid(),
  pack_id uuid not null references packs(id) on delete cascade,

  -- 單字資料
  word text not null,
  definition text,               -- 中文定義
  part_of_speech text,           -- 詞性：n., v., adj., adv....
  example_sentence text,         -- 例句
  phonetic text,                 -- 音標

  -- 排序
  sort_order integer default 0,

  -- 時間戳記
  created_at timestamp with time zone default now()
);

-- 索引
create index idx_pack_items_pack_id on pack_items(pack_id);
create index idx_pack_items_word on pack_items(word);

-- =====================================================
-- 3. INVITE_TOKENS: 邀請碼（用於分享單字包）
-- =====================================================
create table if not exists invite_tokens (
  id uuid primary key default gen_random_uuid(),

  -- 關聯
  pack_id uuid not null references packs(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,

  -- Token 資訊
  token text unique not null,        -- 邀請碼（短碼或 UUID）

  -- 使用限制
  max_uses integer,                  -- 最大使用次數（null = 無限）
  current_uses integer default 0,    -- 目前使用次數
  expires_at timestamp with time zone, -- 過期時間（null = 永不過期）

  -- 狀態
  is_active boolean default true,

  -- 時間戳記
  created_at timestamp with time zone default now()
);

-- 索引
create index idx_invite_tokens_token on invite_tokens(token);
create index idx_invite_tokens_pack_id on invite_tokens(pack_id);

-- =====================================================
-- 4. USER_PACK_CLAIMS: 使用者領取的單字包
-- =====================================================
create table if not exists user_pack_claims (
  id uuid primary key default gen_random_uuid(),

  -- 關聯
  user_id uuid not null references auth.users(id) on delete cascade,
  pack_id uuid not null references packs(id) on delete cascade,
  claimed_via_token uuid references invite_tokens(id) on delete set null,

  -- 學習進度
  progress integer default 0,        -- 學習進度百分比 0-100
  last_studied_at timestamp with time zone,

  -- 時間戳記
  claimed_at timestamp with time zone default now(),

  -- 確保同一使用者不會重複領取同一包
  unique(user_id, pack_id)
);

-- 索引
create index idx_user_pack_claims_user_id on user_pack_claims(user_id);
create index idx_user_pack_claims_pack_id on user_pack_claims(pack_id);

-- =====================================================
-- 5. ROW LEVEL SECURITY (RLS)
-- =====================================================

-- 啟用 RLS
alter table packs enable row level security;
alter table pack_items enable row level security;
alter table invite_tokens enable row level security;
alter table user_pack_claims enable row level security;

-- ----- PACKS RLS -----

-- 任何人都可以查看公開的 pack
create policy "Public packs are viewable by everyone"
  on packs for select
  using (is_public = true and is_active = true);

-- 使用者可以查看自己建立的 pack
create policy "Users can view own packs"
  on packs for select
  using (auth.uid() = created_by);

-- 使用者可以查看已領取的 pack
create policy "Users can view claimed packs"
  on packs for select
  using (
    exists (
      select 1 from user_pack_claims
      where user_pack_claims.pack_id = packs.id
      and user_pack_claims.user_id = auth.uid()
    )
  );

-- 使用者可以建立 pack
create policy "Authenticated users can create packs"
  on packs for insert
  with check (auth.uid() = created_by);

-- 使用者可以更新自己的 pack
create policy "Users can update own packs"
  on packs for update
  using (auth.uid() = created_by);

-- 使用者可以刪除自己的 pack
create policy "Users can delete own packs"
  on packs for delete
  using (auth.uid() = created_by);

-- ----- PACK_ITEMS RLS -----

-- 可以查看有權限的 pack 的 items
create policy "Users can view items of accessible packs"
  on pack_items for select
  using (
    exists (
      select 1 from packs
      where packs.id = pack_items.pack_id
      and (
        packs.is_public = true
        or packs.created_by = auth.uid()
        or exists (
          select 1 from user_pack_claims
          where user_pack_claims.pack_id = packs.id
          and user_pack_claims.user_id = auth.uid()
        )
      )
    )
  );

-- Pack 建立者可以新增 items
create policy "Pack owners can insert items"
  on pack_items for insert
  with check (
    exists (
      select 1 from packs
      where packs.id = pack_items.pack_id
      and packs.created_by = auth.uid()
    )
  );

-- Pack 建立者可以更新 items
create policy "Pack owners can update items"
  on pack_items for update
  using (
    exists (
      select 1 from packs
      where packs.id = pack_items.pack_id
      and packs.created_by = auth.uid()
    )
  );

-- Pack 建立者可以刪除 items
create policy "Pack owners can delete items"
  on pack_items for delete
  using (
    exists (
      select 1 from packs
      where packs.id = pack_items.pack_id
      and packs.created_by = auth.uid()
    )
  );

-- ----- INVITE_TOKENS RLS -----

-- 任何人都可以用 token 查詢（用於驗證 token）
create policy "Anyone can validate tokens"
  on invite_tokens for select
  using (is_active = true);

-- Token 建立者可以查看自己的 tokens
create policy "Users can view own tokens"
  on invite_tokens for select
  using (auth.uid() = created_by);

-- Pack 擁有者可以建立 tokens
create policy "Pack owners can create tokens"
  on invite_tokens for insert
  with check (
    exists (
      select 1 from packs
      where packs.id = invite_tokens.pack_id
      and packs.created_by = auth.uid()
    )
  );

-- Token 建立者可以更新（停用）tokens
create policy "Token creators can update tokens"
  on invite_tokens for update
  using (auth.uid() = created_by);

-- Token 建立者可以刪除 tokens
create policy "Token creators can delete tokens"
  on invite_tokens for delete
  using (auth.uid() = created_by);

-- ----- USER_PACK_CLAIMS RLS -----

-- 使用者只能查看自己的 claims
create policy "Users can view own claims"
  on user_pack_claims for select
  using (auth.uid() = user_id);

-- 已登入使用者可以 claim packs
create policy "Authenticated users can claim packs"
  on user_pack_claims for insert
  with check (auth.uid() = user_id);

-- 使用者可以更新自己的 claim（進度等）
create policy "Users can update own claims"
  on user_pack_claims for update
  using (auth.uid() = user_id);

-- 使用者可以刪除自己的 claim（取消收藏）
create policy "Users can delete own claims"
  on user_pack_claims for delete
  using (auth.uid() = user_id);

-- =====================================================
-- 6. FUNCTIONS: 輔助函數
-- =====================================================

-- 函數：領取單字包（含 token 驗證與使用次數更新）
create or replace function claim_pack_with_token(p_token text)
returns json
language plpgsql
security definer
as $$
declare
  v_token_record invite_tokens%rowtype;
  v_pack_record packs%rowtype;
  v_user_id uuid;
  v_existing_claim user_pack_claims%rowtype;
begin
  -- 取得當前使用者
  v_user_id := auth.uid();
  if v_user_id is null then
    return json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  end if;

  -- 查詢 token
  select * into v_token_record
  from invite_tokens
  where token = p_token
  and is_active = true;

  if v_token_record is null then
    return json_build_object('success', false, 'error', 'INVALID_TOKEN');
  end if;

  -- 檢查是否過期
  if v_token_record.expires_at is not null and v_token_record.expires_at < now() then
    return json_build_object('success', false, 'error', 'TOKEN_EXPIRED');
  end if;

  -- 檢查使用次數
  if v_token_record.max_uses is not null and v_token_record.current_uses >= v_token_record.max_uses then
    return json_build_object('success', false, 'error', 'TOKEN_EXHAUSTED');
  end if;

  -- 查詢 pack
  select * into v_pack_record
  from packs
  where id = v_token_record.pack_id
  and is_active = true;

  if v_pack_record is null then
    return json_build_object('success', false, 'error', 'PACK_NOT_FOUND');
  end if;

  -- 檢查是否已領取
  select * into v_existing_claim
  from user_pack_claims
  where user_id = v_user_id
  and pack_id = v_pack_record.id;

  if v_existing_claim is not null then
    return json_build_object(
      'success', true,
      'already_claimed', true,
      'pack_id', v_pack_record.id,
      'pack_title', v_pack_record.title
    );
  end if;

  -- 新增 claim
  insert into user_pack_claims (user_id, pack_id, claimed_via_token)
  values (v_user_id, v_pack_record.id, v_token_record.id);

  -- 更新 token 使用次數
  update invite_tokens
  set current_uses = current_uses + 1
  where id = v_token_record.id;

  return json_build_object(
    'success', true,
    'already_claimed', false,
    'pack_id', v_pack_record.id,
    'pack_title', v_pack_record.title
  );
end;
$$;

-- 函數：產生短碼 token
create or replace function generate_short_token(length int default 8)
returns text
language plpgsql
as $$
declare
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i int;
begin
  for i in 1..length loop
    result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  end loop;
  return result;
end;
$$;

-- =====================================================
-- 7. SAMPLE DATA (可選 - 測試用)
-- =====================================================

-- 取消註解以下區塊來插入測試資料
/*
-- 插入測試 pack（需要先有使用者）
insert into packs (id, title, description, theme, difficulty, is_public, created_by)
values
  ('11111111-1111-1111-1111-111111111111', '全球暖化核心詞彙', '探討全球暖化相關的核心詞彙', '環境議題', '中高級', false, null),
  ('22222222-2222-2222-2222-222222222222', '少子化議題詞彙', '討論少子化現象的相關詞彙', '社會議題', '中級', false, null);

-- 插入測試單字
insert into pack_items (pack_id, word, definition, part_of_speech, example_sentence, sort_order)
values
  ('11111111-1111-1111-1111-111111111111', 'climate change', '氣候變遷', 'n.', 'Climate change is affecting weather patterns worldwide.', 1),
  ('11111111-1111-1111-1111-111111111111', 'greenhouse effect', '溫室效應', 'n.', 'The greenhouse effect traps heat in the atmosphere.', 2),
  ('11111111-1111-1111-1111-111111111111', 'carbon footprint', '碳足跡', 'n.', 'We should reduce our carbon footprint.', 3);

-- 插入測試 token
insert into invite_tokens (pack_id, token, created_by)
values
  ('11111111-1111-1111-1111-111111111111', 'CLIMATE2024', null),
  ('22222222-2222-2222-2222-222222222222', 'BIRTH2024', null);
*/

-- =====================================================
-- 完成！
-- =====================================================

-- #####################################################################
-- #  2-4. Pack column additions
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/migrations/add_audio_to_pack_items.sql
--  pack_items.audio_url / example_audio_url -- REQUIRED by S3 (TTS)
-- =====================================================================
-- 為 pack_items 加入發音欄位
ALTER TABLE pack_items ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE pack_items ADD COLUMN IF NOT EXISTS example_audio_url TEXT;


-- =====================================================================
--  SOURCE: supabase/migrations/add_skill_type_to_packs.sql
--  packs.skill_type
-- =====================================================================
-- =====================================================
-- Migration: 新增 skill_type 欄位到 packs 表
-- 用於區分英文能力類型：單字、寫作、閱讀等
-- =====================================================

-- 新增欄位
ALTER TABLE packs ADD COLUMN IF NOT EXISTS skill_type text;

-- 更新現有資料（目前只有一筆，是閱讀類型）
UPDATE packs SET skill_type = 'reading' WHERE skill_type IS NULL;

-- 建立索引（方便篩選）
CREATE INDEX IF NOT EXISTS idx_packs_skill_type ON packs(skill_type);

-- =====================================================
-- skill_type 可選值說明：
-- - vocabulary: 單字
-- - writing: 寫作
-- - reading: 閱讀
-- - listening: 聽力（未來擴充）
-- - grammar: 文法（未來擴充）
-- =====================================================


-- =====================================================================
--  SOURCE: supabase/migrations/add_site_to_user_pack_claims.sql
--  user_pack_claims.site + claim_pack_with_token(2-arg) that HONOURS p_site -- deliberately overwritten in section 8
-- =====================================================================
-- =====================================================
-- Migration: 為 user_pack_claims 加入 site 欄位
-- 用於區分不同子站的單字包領取
-- =====================================================

-- 1. 新增 site 欄位
ALTER TABLE user_pack_claims
ADD COLUMN IF NOT EXISTS site text DEFAULT 'gsat';

-- 2. 建立索引以加速查詢
CREATE INDEX IF NOT EXISTS idx_user_pack_claims_site ON user_pack_claims(site);

-- 3. 更新 claim_pack_with_token 函數，加入 site 參數
CREATE OR REPLACE FUNCTION claim_pack_with_token(p_token text, p_site text DEFAULT 'gsat')
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_token_record invite_tokens%rowtype;
  v_pack_record packs%rowtype;
  v_user_id uuid;
  v_existing_claim user_pack_claims%rowtype;
BEGIN
  -- 取得當前使用者
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  END IF;

  -- 查詢 token
  SELECT * INTO v_token_record
  FROM invite_tokens
  WHERE token = p_token
  AND is_active = true;

  IF v_token_record IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'INVALID_TOKEN');
  END IF;

  -- 檢查是否過期
  IF v_token_record.expires_at IS NOT NULL AND v_token_record.expires_at < now() THEN
    RETURN json_build_object('success', false, 'error', 'TOKEN_EXPIRED');
  END IF;

  -- 檢查使用次數
  IF v_token_record.max_uses IS NOT NULL AND v_token_record.current_uses >= v_token_record.max_uses THEN
    RETURN json_build_object('success', false, 'error', 'TOKEN_EXHAUSTED');
  END IF;

  -- 查詢 pack
  SELECT * INTO v_pack_record
  FROM packs
  WHERE id = v_token_record.pack_id
  AND is_active = true;

  IF v_pack_record IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'PACK_NOT_FOUND');
  END IF;

  -- 檢查是否在同一站點已領取（允許不同站點重複領取）
  SELECT * INTO v_existing_claim
  FROM user_pack_claims
  WHERE user_id = v_user_id
  AND pack_id = v_pack_record.id
  AND site = p_site;

  IF v_existing_claim IS NOT NULL THEN
    RETURN json_build_object(
      'success', true,
      'already_claimed', true,
      'pack_id', v_pack_record.id,
      'pack_title', v_pack_record.title,
      'site', p_site
    );
  END IF;

  -- 新增 claim（包含 site）
  INSERT INTO user_pack_claims (user_id, pack_id, claimed_via_token, site)
  VALUES (v_user_id, v_pack_record.id, v_token_record.id, p_site);

  -- 更新 token 使用次數
  UPDATE invite_tokens
  SET current_uses = current_uses + 1
  WHERE id = v_token_record.id;

  RETURN json_build_object(
    'success', true,
    'already_claimed', false,
    'pack_id', v_pack_record.id,
    'pack_title', v_pack_record.title,
    'site', p_site
  );
END;
$$;

-- 4. 更新 unique constraint（如果需要允許同用戶在不同站領取同一包）
-- 先移除舊的 unique constraint
ALTER TABLE user_pack_claims DROP CONSTRAINT IF EXISTS user_pack_claims_user_id_pack_id_key;

-- 新增包含 site 的 unique constraint
ALTER TABLE user_pack_claims ADD CONSTRAINT user_pack_claims_user_id_pack_id_site_key UNIQUE (user_id, pack_id, site);

-- =====================================================
-- 完成！
-- =====================================================

-- #####################################################################
-- #  5. claim_pack_with_token 1-arg, current version
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/migrations/update_claim_pack_function.sql
--  replaces the 1-arg version from schema.sql
-- =====================================================================
-- =====================================================
-- Migration: 更新 claim_pack_with_token 函數
-- 修復重複領取時的錯誤處理
-- =====================================================

-- 重新建立函數（會覆蓋舊版本）
create or replace function claim_pack_with_token(p_token text)
returns json
language plpgsql
security definer
as $$
declare
  v_token_record invite_tokens%rowtype;
  v_pack_record packs%rowtype;
  v_user_id uuid;
  v_existing_claim user_pack_claims%rowtype;
begin
  -- 取得當前使用者
  v_user_id := auth.uid();
  if v_user_id is null then
    return json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  end if;

  -- 查詢 token
  select * into v_token_record
  from invite_tokens
  where token = p_token
  and is_active = true;

  if v_token_record is null then
    return json_build_object('success', false, 'error', 'INVALID_TOKEN');
  end if;

  -- 檢查是否過期
  if v_token_record.expires_at is not null and v_token_record.expires_at < now() then
    return json_build_object('success', false, 'error', 'TOKEN_EXPIRED');
  end if;

  -- 檢查使用次數
  if v_token_record.max_uses is not null and v_token_record.current_uses >= v_token_record.max_uses then
    return json_build_object('success', false, 'error', 'TOKEN_EXHAUSTED');
  end if;

  -- 查詢 pack
  select * into v_pack_record
  from packs
  where id = v_token_record.pack_id
  and is_active = true;

  if v_pack_record is null then
    return json_build_object('success', false, 'error', 'PACK_NOT_FOUND');
  end if;

  -- 檢查是否已領取（在 INSERT 之前檢查）
  select * into v_existing_claim
  from user_pack_claims
  where user_id = v_user_id
  and pack_id = v_pack_record.id;

  if v_existing_claim is not null then
    return json_build_object(
      'success', true,
      'already_claimed', true,
      'pack_id', v_pack_record.id,
      'pack_title', v_pack_record.title
    );
  end if;

  -- 新增 claim
  insert into user_pack_claims (user_id, pack_id, claimed_via_token)
  values (v_user_id, v_pack_record.id, v_token_record.id);

  -- 更新 token 使用次數
  update invite_tokens
  set current_uses = current_uses + 1
  where id = v_token_record.id;

  return json_build_object(
    'success', true,
    'already_claimed', false,
    'pack_id', v_pack_record.id,
    'pack_title', v_pack_record.title
  );
end;
$$;

-- #####################################################################
-- #  6. user_profiles + is_admin()
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/migrations/create_user_profiles_table.sql
--  user_profiles, is_admin() [hard-coded email -- finding 9.6], admin_get_all_users, admin_get_user_stats. MUST precede section 7.
-- =====================================================================
-- =====================================================
-- User Profiles Table
-- 儲存使用者背景資料（年級、產品等）
-- =====================================================

-- 建立 user_profiles 表
CREATE TABLE IF NOT EXISTS user_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- 基本資料
  display_name TEXT,

  -- 產品類型 (gsat/toeic/kids)
  product TEXT NOT NULL DEFAULT 'gsat',

  -- 年級/身分
  -- GSAT: 國一、國二、國三、高一、高二、高三、重考
  -- TOEIC: 大學生、上班族、其他
  -- KIDS: 小班、中班、大班、小一~小六
  grade TEXT,

  -- 選填資料
  school TEXT,

  -- 時間戳記
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- 確保每個使用者只有一筆資料
  UNIQUE(user_id)
);

-- 建立索引
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_product ON user_profiles(product);
CREATE INDEX IF NOT EXISTS idx_user_profiles_grade ON user_profiles(grade);

-- 啟用 RLS
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- RLS 政策：使用者只能存取自己的資料
CREATE POLICY "Users can view own profile"
  ON user_profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own profile"
  ON user_profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own profile"
  ON user_profiles FOR UPDATE
  USING (auth.uid() = user_id);

-- =====================================================
-- RPC Functions
-- =====================================================

-- 取得使用者 Profile
CREATE OR REPLACE FUNCTION get_user_profile()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_profile user_profiles%ROWTYPE;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  END IF;

  SELECT * INTO v_profile
  FROM user_profiles
  WHERE user_id = v_user_id;

  IF v_profile IS NULL THEN
    -- 沒有 profile，回傳 null 但標記成功
    RETURN json_build_object(
      'success', true,
      'profile', null,
      'has_profile', false
    );
  END IF;

  RETURN json_build_object(
    'success', true,
    'has_profile', true,
    'profile', json_build_object(
      'id', v_profile.id,
      'user_id', v_profile.user_id,
      'display_name', v_profile.display_name,
      'product', v_profile.product,
      'grade', v_profile.grade,
      'school', v_profile.school,
      'created_at', v_profile.created_at,
      'updated_at', v_profile.updated_at
    )
  );
END;
$$;

-- 更新/建立使用者 Profile
CREATE OR REPLACE FUNCTION upsert_user_profile(
  p_product TEXT DEFAULT 'gsat',
  p_grade TEXT DEFAULT NULL,
  p_display_name TEXT DEFAULT NULL,
  p_school TEXT DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_profile user_profiles%ROWTYPE;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  END IF;

  -- Upsert profile
  INSERT INTO user_profiles (user_id, product, grade, display_name, school)
  VALUES (v_user_id, p_product, p_grade, p_display_name, p_school)
  ON CONFLICT (user_id) DO UPDATE SET
    product = COALESCE(EXCLUDED.product, user_profiles.product),
    grade = COALESCE(EXCLUDED.grade, user_profiles.grade),
    display_name = COALESCE(EXCLUDED.display_name, user_profiles.display_name),
    school = COALESCE(EXCLUDED.school, user_profiles.school),
    updated_at = now()
  RETURNING * INTO v_profile;

  RETURN json_build_object(
    'success', true,
    'profile', json_build_object(
      'id', v_profile.id,
      'user_id', v_profile.user_id,
      'display_name', v_profile.display_name,
      'product', v_profile.product,
      'grade', v_profile.grade,
      'school', v_profile.school,
      'created_at', v_profile.created_at,
      'updated_at', v_profile.updated_at
    )
  );
END;
$$;

-- =====================================================
-- Admin Functions (只有 admin 可以使用)
-- =====================================================

-- 檢查是否為 admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_email TEXT;
BEGIN
  SELECT email INTO v_user_email
  FROM auth.users
  WHERE id = auth.uid();

  -- 只有特定 email 是 admin
  RETURN v_user_email = 'nonstopjazz@gmail.com';
END;
$$;

-- Admin: 取得所有使用者資料
CREATE OR REPLACE FUNCTION admin_get_all_users(
  p_product TEXT DEFAULT NULL,
  p_grade TEXT DEFAULT NULL,
  p_limit INTEGER DEFAULT 100,
  p_offset INTEGER DEFAULT 0
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_is_admin BOOLEAN;
  v_users JSON;
  v_total INTEGER;
BEGIN
  -- 檢查是否為 admin
  v_is_admin := is_admin();
  IF NOT v_is_admin THEN
    RETURN json_build_object('success', false, 'error', 'UNAUTHORIZED');
  END IF;

  -- 計算總數
  SELECT COUNT(*) INTO v_total
  FROM auth.users u
  LEFT JOIN user_profiles p ON u.id = p.user_id
  WHERE (p_product IS NULL OR p.product = p_product)
    AND (p_grade IS NULL OR p.grade = p_grade);

  -- 取得使用者列表
  SELECT json_agg(user_data) INTO v_users
  FROM (
    SELECT
      u.id,
      u.email,
      u.created_at AS registered_at,
      u.last_sign_in_at,
      p.display_name,
      p.product,
      p.grade,
      p.school,
      p.created_at AS profile_created_at,
      p.updated_at AS profile_updated_at
    FROM auth.users u
    LEFT JOIN user_profiles p ON u.id = p.user_id
    WHERE (p_product IS NULL OR p.product = p_product)
      AND (p_grade IS NULL OR p.grade = p_grade)
    ORDER BY u.created_at DESC
    LIMIT p_limit
    OFFSET p_offset
  ) AS user_data;

  RETURN json_build_object(
    'success', true,
    'users', COALESCE(v_users, '[]'::json),
    'total', v_total,
    'limit', p_limit,
    'offset', p_offset
  );
END;
$$;

-- Admin: 取得使用者統計
CREATE OR REPLACE FUNCTION admin_get_user_stats()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_is_admin BOOLEAN;
  v_total_users INTEGER;
  v_users_with_profile INTEGER;
  v_grade_stats JSON;
  v_product_stats JSON;
BEGIN
  -- 檢查是否為 admin
  v_is_admin := is_admin();
  IF NOT v_is_admin THEN
    RETURN json_build_object('success', false, 'error', 'UNAUTHORIZED');
  END IF;

  -- 總使用者數
  SELECT COUNT(*) INTO v_total_users FROM auth.users;

  -- 有填寫 profile 的使用者數
  SELECT COUNT(*) INTO v_users_with_profile FROM user_profiles;

  -- 各年級人數統計
  SELECT json_agg(grade_data) INTO v_grade_stats
  FROM (
    SELECT grade, COUNT(*) as count
    FROM user_profiles
    WHERE grade IS NOT NULL
    GROUP BY grade
    ORDER BY count DESC
  ) AS grade_data;

  -- 各產品人數統計
  SELECT json_agg(product_data) INTO v_product_stats
  FROM (
    SELECT product, COUNT(*) as count
    FROM user_profiles
    GROUP BY product
    ORDER BY count DESC
  ) AS product_data;

  RETURN json_build_object(
    'success', true,
    'total_users', v_total_users,
    'users_with_profile', v_users_with_profile,
    'grade_stats', COALESCE(v_grade_stats, '[]'::json),
    'product_stats', COALESCE(v_product_stats, '[]'::json)
  );
END;
$$;

-- #####################################################################
-- #  7. premium_memberships  (installs findings 9.3 / 9.15 / 9.5)
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/migrations/add_premium_memberships.sql
--  premium_memberships, is_premium_member, claim_pack_with_token(2-arg) that IGNORES p_site, and the PRE-A1 admin_grant_premium / admin_revoke_premium
-- =====================================================================
-- =====================================================
-- Premium Memberships: 精華會員資格管理
-- =====================================================

-- 1. 建立 premium_memberships 表
CREATE TABLE IF NOT EXISTS premium_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  granted_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone, -- null = 永不過期
  is_active boolean DEFAULT true,      -- false = 手動收回
  granted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  notes text,                          -- 備註（例如「2025暑期班」）

  created_at timestamp with time zone DEFAULT now()
);

CREATE INDEX idx_premium_memberships_user_id ON premium_memberships(user_id);
CREATE INDEX idx_premium_memberships_active ON premium_memberships(is_active, expires_at);

-- RLS
ALTER TABLE premium_memberships ENABLE ROW LEVEL SECURITY;

-- 使用者可查看自己的會員資格
CREATE POLICY "Users can view own memberships"
  ON premium_memberships FOR SELECT
  USING (auth.uid() = user_id);

-- Admin 可完整操作（透過 security definer 函數處理）

-- 2. packs 表新增 is_premium 欄位
ALTER TABLE packs
ADD COLUMN IF NOT EXISTS is_premium boolean NOT NULL DEFAULT false;

-- 3. 建立檢查函數：使用者是否為有效 premium 會員
CREATE OR REPLACE FUNCTION is_premium_member(p_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM premium_memberships
    WHERE user_id = p_user_id
      AND is_active = true
      AND (expires_at IS NULL OR expires_at > now())
  );
END;
$$;

-- 4. 更新 claim_pack_with_token 函數，加入 premium 檢查
CREATE OR REPLACE FUNCTION claim_pack_with_token(p_token text, p_site text DEFAULT NULL)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_token_record invite_tokens%rowtype;
  v_pack_record packs%rowtype;
  v_user_id uuid;
  v_existing_claim user_pack_claims%rowtype;
BEGIN
  -- 取得當前使用者
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  END IF;

  -- 查詢 token
  SELECT * INTO v_token_record
  FROM invite_tokens
  WHERE token = p_token
  AND is_active = true;

  IF v_token_record IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'INVALID_TOKEN');
  END IF;

  -- 檢查是否過期
  IF v_token_record.expires_at IS NOT NULL AND v_token_record.expires_at < now() THEN
    RETURN json_build_object('success', false, 'error', 'TOKEN_EXPIRED');
  END IF;

  -- 檢查使用次數
  IF v_token_record.max_uses IS NOT NULL AND v_token_record.current_uses >= v_token_record.max_uses THEN
    RETURN json_build_object('success', false, 'error', 'TOKEN_EXHAUSTED');
  END IF;

  -- 查詢 pack
  SELECT * INTO v_pack_record
  FROM packs
  WHERE id = v_token_record.pack_id
  AND is_active = true;

  IF v_pack_record IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'PACK_NOT_FOUND');
  END IF;

  -- ★ Premium 檢查：如果是精華包，確認使用者是否為 premium 會員
  IF v_pack_record.is_premium AND NOT is_premium_member(v_user_id) THEN
    RETURN json_build_object('success', false, 'error', 'PREMIUM_REQUIRED');
  END IF;

  -- 檢查是否已領取
  SELECT * INTO v_existing_claim
  FROM user_pack_claims
  WHERE user_id = v_user_id
  AND pack_id = v_pack_record.id;

  IF v_existing_claim IS NOT NULL THEN
    RETURN json_build_object(
      'success', true,
      'already_claimed', true,
      'pack_id', v_pack_record.id,
      'pack_title', v_pack_record.title
    );
  END IF;

  -- 新增 claim
  INSERT INTO user_pack_claims (user_id, pack_id, claimed_via_token)
  VALUES (v_user_id, v_pack_record.id, v_token_record.id);

  -- 更新 token 使用次數
  UPDATE invite_tokens
  SET current_uses = current_uses + 1
  WHERE id = v_token_record.id;

  RETURN json_build_object(
    'success', true,
    'already_claimed', false,
    'pack_id', v_pack_record.id,
    'pack_title', v_pack_record.title
  );
END;
$$;

-- 5. Admin 管理函數：授予 premium 資格
CREATE OR REPLACE FUNCTION admin_grant_premium(
  p_user_id uuid,
  p_expires_at timestamp with time zone DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_admin_id uuid;
BEGIN
  v_admin_id := auth.uid();

  INSERT INTO premium_memberships (user_id, expires_at, granted_by, notes)
  VALUES (p_user_id, p_expires_at, v_admin_id, p_notes);

  RETURN json_build_object('success', true);
END;
$$;

-- 6. Admin 管理函數：收回 premium 資格
CREATE OR REPLACE FUNCTION admin_revoke_premium(p_membership_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE premium_memberships
  SET is_active = false
  WHERE id = p_membership_id;

  RETURN json_build_object('success', true);
END;
$$;

-- #####################################################################
-- #  8. Admin RLS fix  (requires is_admin from section 6)
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/migrations/fix_premium_memberships_admin_rls.sql
--  Admins can view all memberships
-- =====================================================================
-- 修復：允許 Admin 查看所有 premium_memberships
-- 原本只有 "Users can view own memberships" 導致 admin 看不到其他使用者的 Premium 狀態

CREATE POLICY "Admins can view all memberships"
  ON premium_memberships FOR SELECT
  USING (is_admin());

-- #####################################################################
-- #  9-10. Cron path tables
-- #####################################################################

-- =====================================================================
--  SOURCE: supabase/migrations/create_push_subscriptions_table.sql
--  push_subscriptions -- REQUIRED by S4
-- =====================================================================
-- =====================================================
-- Push Subscriptions: Web Push 通知訂閱管理
-- =====================================================

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, endpoint)
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own subscriptions"
  ON push_subscriptions FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own subscriptions"
  ON push_subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own subscriptions"
  ON push_subscriptions FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can update own subscriptions"
  ON push_subscriptions FOR UPDATE USING (auth.uid() = user_id);


-- =====================================================================
--  SOURCE: supabase/migrations/create_user_stats_table.sql
--  user_stats -- REQUIRED by S4 targeting
-- =====================================================================
-- =====================================================
-- Migration: 建立 user_stats 表
-- 用於儲存使用者的學習統計（跨裝置同步）
-- =====================================================

-- 建立 user_stats 表
CREATE TABLE IF NOT EXISTS user_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  streak_days INTEGER NOT NULL DEFAULT 0,
  last_study_date DATE,
  total_review_count INTEGER NOT NULL DEFAULT 0,
  total_words_learned INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- 建立索引
CREATE INDEX IF NOT EXISTS idx_user_stats_user_id ON user_stats(user_id);

-- 啟用 RLS
ALTER TABLE user_stats ENABLE ROW LEVEL SECURITY;

-- RLS 政策：使用者只能查看自己的統計
CREATE POLICY "Users can view own stats"
  ON user_stats FOR SELECT
  USING (auth.uid() = user_id);

-- RLS 政策：使用者可以新增自己的統計
CREATE POLICY "Users can insert own stats"
  ON user_stats FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS 政策：使用者可以更新自己的統計
CREATE POLICY "Users can update own stats"
  ON user_stats FOR UPDATE
  USING (auth.uid() = user_id);

-- 建立更新 streak 的函數
CREATE OR REPLACE FUNCTION update_user_streak(
  p_review_count INTEGER DEFAULT 1,
  p_words_learned INTEGER DEFAULT 0
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_stats user_stats%ROWTYPE;
  v_today DATE;
  v_yesterday DATE;
  v_new_streak INTEGER;
BEGIN
  -- 取得當前使用者
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  END IF;

  v_today := CURRENT_DATE;
  v_yesterday := v_today - INTERVAL '1 day';

  -- 查詢現有統計
  SELECT * INTO v_stats
  FROM user_stats
  WHERE user_id = v_user_id;

  IF v_stats IS NULL THEN
    -- 新使用者，建立記錄
    INSERT INTO user_stats (user_id, streak_days, last_study_date, total_review_count, total_words_learned)
    VALUES (v_user_id, 1, v_today, p_review_count, p_words_learned)
    RETURNING * INTO v_stats;

    RETURN json_build_object(
      'success', true,
      'streak_days', v_stats.streak_days,
      'total_review_count', v_stats.total_review_count,
      'total_words_learned', v_stats.total_words_learned,
      'is_new_day', true
    );
  END IF;

  -- 計算新的 streak
  IF v_stats.last_study_date = v_today THEN
    -- 今天已經學習過，只更新計數
    v_new_streak := v_stats.streak_days;

    UPDATE user_stats
    SET
      total_review_count = total_review_count + p_review_count,
      total_words_learned = GREATEST(total_words_learned, p_words_learned),
      updated_at = now()
    WHERE user_id = v_user_id
    RETURNING * INTO v_stats;

    RETURN json_build_object(
      'success', true,
      'streak_days', v_stats.streak_days,
      'total_review_count', v_stats.total_review_count,
      'total_words_learned', v_stats.total_words_learned,
      'is_new_day', false
    );
  ELSIF v_stats.last_study_date = v_yesterday THEN
    -- 昨天有學習，連續天數 +1
    v_new_streak := v_stats.streak_days + 1;
  ELSE
    -- 中斷了，重新開始
    v_new_streak := 1;
  END IF;

  -- 更新統計
  UPDATE user_stats
  SET
    streak_days = v_new_streak,
    last_study_date = v_today,
    total_review_count = total_review_count + p_review_count,
    total_words_learned = GREATEST(total_words_learned, p_words_learned),
    updated_at = now()
  WHERE user_id = v_user_id
  RETURNING * INTO v_stats;

  RETURN json_build_object(
    'success', true,
    'streak_days', v_stats.streak_days,
    'total_review_count', v_stats.total_review_count,
    'total_words_learned', v_stats.total_words_learned,
    'is_new_day', true
  );
END;
$$;

-- 建立取得統計的函數
CREATE OR REPLACE FUNCTION get_user_stats()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_stats user_stats%ROWTYPE;
  v_today DATE;
  v_yesterday DATE;
  v_actual_streak INTEGER;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  END IF;

  v_today := CURRENT_DATE;
  v_yesterday := v_today - INTERVAL '1 day';

  SELECT * INTO v_stats
  FROM user_stats
  WHERE user_id = v_user_id;

  IF v_stats IS NULL THEN
    -- 沒有記錄，回傳預設值
    RETURN json_build_object(
      'success', true,
      'streak_days', 0,
      'total_review_count', 0,
      'total_words_learned', 0,
      'last_study_date', NULL
    );
  END IF;

  -- 檢查 streak 是否仍然有效
  IF v_stats.last_study_date = v_today OR v_stats.last_study_date = v_yesterday THEN
    v_actual_streak := v_stats.streak_days;
  ELSE
    -- Streak 已中斷（但不更新資料庫，等下次學習時才更新）
    v_actual_streak := 0;
  END IF;

  RETURN json_build_object(
    'success', true,
    'streak_days', v_actual_streak,
    'total_review_count', v_stats.total_review_count,
    'total_words_learned', v_stats.total_words_learned,
    'last_study_date', v_stats.last_study_date
  );
END;
$$;


-- #####################################################################
-- #  11. app_admins
-- #####################################################################
-- =====================================================================
--  SOURCE: hand-written -- there is NO DDL for this table in the repo.
--  Reconstructed from production discovery Q07 + Q18, per
--  STAGING_PLAN.md section 3.1.
--
--  In Production this table gates exactly one thing: the site_settings
--  UPDATE policy (audit 4.3, REFUTED as a finding -- it is correctly
--  admin-gated). site_settings is not created on staging, so this table
--  exists here only so the shape matches and the ADMIN fixture has a row.
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.app_admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE public.app_admins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own admin row" ON public.app_admins;
CREATE POLICY "Users can view own admin row"
  ON public.app_admins FOR SELECT
  USING (auth.uid() = user_id);

COMMIT;

-- #####################################################################
-- #  12. Pre-A1 premium function bodies + EXACT production ACL
-- #####################################################################

-- =====================================================================
--  SOURCE: docs/phase-0.5b/A1-premium-functions.rollback.sql
--  STAGING_PLAN.md section 3.1 requires the CURRENT PRODUCTION bodies, taken from the rollback file. It carries its own BEGIN/COMMIT and the exact pre-A1 EXECUTE ACL (PUBLIC + anon), which the migration files do not. Idempotent: re-creates the same bodies section 7 installed, then fixes the grants.
-- =====================================================================
-- =====================================================================
--  ROLLBACK for A1-premium-functions.sql
--  Restores the EXACT production definitions captured by Q15 on
--  2026-08-23, verbatim.
-- =====================================================================
--
--  ⚠️  Applying this rollback REINSTATES CRITICAL security finding 9.3:
--      both functions become executable by PUBLIC (including anon) with
--      no authorization check, and finding 9.15 (revocation silently
--      failing) returns with them.
--
--      Use it only if the A1 change causes a worse problem, and treat
--      the window as an active exposure.
--
--  This rollback changes NO DATA. Any memberships granted, extended or
--  revoked while the A1 version was live remain exactly as they are —
--  those are legitimate administrator actions, not artefacts of the
--  change. In particular, if a revoke ran under A1 and correctly
--  deactivated two rows, rolling back does NOT reactivate them.
--
--  Source of truth: the `full_definition` column of Q15's output. The
--  bodies below are reproduced unaltered, including the absence of
--  SET search_path.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
--  1. Restore admin_grant_premium to its pre-A1 definition
--     (no admin check, no search_path, unconditional INSERT)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_grant_premium(
  p_user_id uuid,
  p_expires_at timestamp with time zone DEFAULT NULL::timestamp with time zone,
  p_notes text DEFAULT NULL::text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_admin_id uuid;
BEGIN
  v_admin_id := auth.uid();

  INSERT INTO premium_memberships (user_id, expires_at, granted_by, notes)
  VALUES (p_user_id, p_expires_at, v_admin_id, p_notes);

  RETURN json_build_object('success', true);
END;
$function$;


-- ---------------------------------------------------------------------
--  2. Restore admin_revoke_premium to its pre-A1 definition
--     (no admin check, no search_path, single-row revoke by id)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_revoke_premium(p_membership_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE premium_memberships
  SET is_active = false
  WHERE id = p_membership_id;

  RETURN json_build_object('success', true);
END;
$function$;


-- ---------------------------------------------------------------------
--  3. Restore the pre-A1 EXECUTE privileges
-- ---------------------------------------------------------------------
--  Original ACL, from Q15:
--    {=X/postgres, postgres=X/postgres, anon=X/postgres,
--     authenticated=X/postgres, service_role=X/postgres}
--
--  "=X/postgres" is EXECUTE granted to PUBLIC. Restoring it is what
--  makes this rollback dangerous; it is included so the rollback is
--  faithful rather than partial.
-- ---------------------------------------------------------------------
GRANT EXECUTE ON FUNCTION public.admin_grant_premium(uuid, timestamp with time zone, text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_grant_premium(uuid, timestamp with time zone, text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_grant_premium(uuid, timestamp with time zone, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_grant_premium(uuid, timestamp with time zone, text) TO service_role;

GRANT EXECUTE ON FUNCTION public.admin_revoke_premium(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_revoke_premium(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_revoke_premium(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_revoke_premium(uuid) TO service_role;

COMMIT;

-- ---------------------------------------------------------------------
--  Confirm the rollback landed
-- ---------------------------------------------------------------------
--  Expect: proconfig = NULL (no search_path) and an ACL containing
--  "=X/postgres" for both functions.
--
--  SELECT p.proname,
--         pg_get_function_identity_arguments(p.oid) AS args,
--         COALESCE(p.proconfig::text, '(no search_path)') AS proconfig,
--         p.proacl::text AS execute_acl
--  FROM pg_proc p
--  JOIN pg_namespace n ON n.oid = p.pronamespace
--  WHERE n.nspname = 'public'
--    AND p.proname IN ('admin_grant_premium','admin_revoke_premium')
--  ORDER BY p.proname;
-- =====================================================================

-- =====================================================================
--  DONE. Verify with the query below.
--
--  Expect for BOTH admin_grant_premium and admin_revoke_premium:
--    proconfig    = (no search_path)
--    execute_acl  contains  =X/          <- EXECUTE granted to PUBLIC
--
--  If proconfig already shows search_path=, the A1 fix was applied by
--  mistake. Staging must start BROKEN. Re-run this script.
-- =====================================================================
-- SELECT p.proname,
--        pg_get_function_identity_arguments(p.oid) AS args,
--        COALESCE(p.proconfig::text, '(no search_path)') AS proconfig,
--        p.proacl::text AS execute_acl
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public'
--   AND p.proname IN ('admin_grant_premium','admin_revoke_premium')
-- ORDER BY p.proname;
